[package]
name = "mybin-cmd"
version = "0.1.0"
authors = ["Zhe Jiang <nju.jiangzhe@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bitflags = "1.2"
thiserror = "1.0"
mybin-parser = { version = "0.1.0", path = "../mybin-parser" }
