[package]
name = "bytes-parser"
version = "0.1.0"
authors = ["Zhe Jiang <nju.jiangzhe@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
thiserror = "1.0"
futures = "0.3"
bytes = "1.0"

[dev-dependencies]
smol-potat = "1.1"
smol = "1.2.5"
async-executor = "1.4"